### ISSUE TITLE
Version 6.27.1 Not allowing switch to SMS

### ISSUE THREAD

**Issue by WeareTheDraiken** [alexlance/signal-android-classic#7]
Functionality to hold and switch to SMS is not working instead leads to possibility of crashing app.

Tested on Arm64 version.

**Comment by alexlance** [comment]
Hi there, when you say possibility - does it sometimes still work ok?

(does it depend on which contact you're sending to?)

**Comment by WeareTheDraiken** [comment]
@alexlance No any contact

**Comment by WeareTheDraiken** [comment]
@alexlance it never works besides any contact, been trying repeatedly.

**Comment by alexlance** [comment]
Do you still get the popup with two options:

 - Schedule message
 - Insecure SMS
 
and when you choose "Insecure SMS" the app crashes?

**Comment by WeareTheDraiken** [comment]
@alexlance no schedule messages, no insecure method, none show up.

If I press and hold the enter key to make them appear, the app either crashes or opens as if to add an image.

**Comment by alexlance** [comment]
One thing you could try, open the app, perform the steps that make it crash, then re-open the app go to Help -> Debug log, then click the `. . .` menu in the top-right, and Save the log. Then open it up on a proper computer and looks for any helpful messages that might help tell you why the app crashed.

If nothing jumps out feel free to send it my way (signal-issue7@alexlance.com), but I'm not that familiar with the contents of the log file, it may contain sensitive information - although presumably if Signal have put a giant "post this log online" button there, it likely is fairly clean. 

I'm currently using version 6.26.2 and SMS sending/receiving definitely works fine. So it's likely something changed between that version and 6.27.1. Currently looking through the git logs.

**Comment by WeareTheDraiken** [comment]
Yeah @alexlance I feel something has changed since holding the enter key acts now as a way to enter image and other files, I think its contrasting with how you forked it, gonna have to go back to 6.26.3.

I've sent you the debug.

**Comment by alexlance** [comment]
I've received it, thank you. These log entries jumped out:

```
08-06 07:28:24.629 24548 24548 E SignalUncaughtException: java.lang.NullPointerException
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at org.thoughtcrime.securesms.components.SendButton.showSendTypeContextMenu(SendButton.kt:213)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at org.thoughtcrime.securesms.components.SendButton.onLongClick(SendButton.kt:188)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.view.View.performLongClickInternal(View.java:7952)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.view.View.performLongClick(View.java:7902)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.view.View.performLongClick(View.java:7920)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.view.View$CheckForLongPress.run(View.java:29317)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.os.Handler.handleCallback(Handler.java:883)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.os.Handler.dispatchMessage(Handler.java:100)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.os.Looper.loop(Looper.java:237)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at android.app.ActivityThread.main(ActivityThread.java:8167)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at java.lang.reflect.Method.invoke(Native Method)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
08-06 07:28:24.629 24548 24548 E SignalUncaughtException:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Which led me to run git log on SendButton.kt and then this thing popped up:

`2023-07-27 938309d125 Clark Chen: Remove SMS popup from CFv2.`

Gah. 

Will keep digging around.

**Comment by WeareTheDraiken** [comment]
"2023-07-27 938309d125 Clark Chen: Remove SMS popup from CFv2."

Seems Signal put something inside to wither remove the feature entirely as possibly it was still there under the hood in the official app.

Or they don't like people creatong forks that still have sms functionality.

I didn't notice this honesty, and I'm honestly glad that you're taking it as seriously atrending to the issue.

I can't express how honestly greatful I am to you always posting forks of thier updates continuously.

**Comment by Particpant** [comment]
_Receiving_ SMS still works. Sending a message in an insecure chat always fails (and the send icon is the secure version.)
In the meantime, what's the best/safest way to downgrade? The normal download / upgrade process wouldn't let me replace this version with the last released version.

Again, thanks for keeping this alive!

**Comment by alexlance** [comment]
Have confirmed these releases all work as expected with sms:
6.26.1, 6.26.2, 6.26.3, 6.26.4

And I've deleted the 6.27.1 release for now. 

Will try and get the problem patched and then push up a new 6.27.1 release.

@Particpant with regard to downgrading an APK - this is very likely to be a dangerous operation. Any Signal upgrades to the database tables or data transformations they make on a normal upgrade aren't likely to be reversible.

The only safe way of going back in time is to restore an older backup file into a fresh install of an older version of Signal.

Now having said that, I did try a test downgrade from 6.24.4 back to 6.24.2 using the Android debugger: 
```
adb shell
pm install -r -d path-to-file.apk
``` 
(-r = replace package, -d = allow downgrade) but I then got the error message:

`Failure [INSTALL_FAILED_VERSION_DOWNGRADE]`

Will keep updating this thread throughout the week - but not likely to be able to do much until next weekend.

ps: @ubergeek77 you might be interested in this issue too.

**Comment by ubergeek77** [comment]
So it begins...

I've just been sitting comfy on the last version of Signal I made a patch for. I'm even missing some features but I don't really care as long as SMS works.

It sucks this is the beginning of the end, but honestly I'm more likely to just stop using Signal than maintain patches for a hostile upstream developer :/

I'll keep an eye on how this plays out, though

**Comment by Particpant** [comment]
@alexlance thanks. I unfortunately didn't have a backup on a prior version. I'll have to try restoring a backup from this version with an old version of the app. :/

**Comment by alexlance** [comment]
I can definitely replicate the bug that @WeareTheDraiken reported in this issue using 6.27.1. However I then built a version of 6.27.4 and the bug was gone (maybe it was an upstream issue in that version).

Unfortunately when I was using my test build of 6.27.4 the "Insecure SMS" option no longer resulted in smses being sent, they were converted to Signal messages automatically.

I dug into the code and it looks like the sms code is experiencing a more thorough excavation in the 6.27.x versions.

The 6.26.x versions still work fine. But I am having trouble figuring out how to proceed with 6.27.

**Comment by WeareTheDraiken** [comment]
@alexlance Honestly I'm truelly grateful you're still at this, I want to say that first. 

I'm not a programmer and my laptop is busted, but I don't know if there would be another way to implement sms into signal besides the original way.

Like I'm just spitballing here ,but I remember back when I was on whatsapp , I would use WhatsApp plus by thirdpaties forking it(Before I really knew about privacy and security) and thhey would add all types of features and stuff to the messenger that made the normal whatsapp obsolete in terms of features.

So I wonder if signal code is to restricted for you to implement it in another way.

Also I don't know if it would be easier for you if it wasn't just you, since doing all this alone I would imagine is a hard task.
Maybe if there's a way someone you trust could also look at it and maybe help out that they would see somthing you couldn't. 

Just my thoughts.

**Comment by Particpant** [comment]
I was unfortunately, unable to restore my backup from 6.27.1 back into one of your older releases.
With luck, the commits that removed SMS functionality were self-contained, so it'd be a matter of just selecting some isolated changes to back out. Again, thank you for trying to keep this alive!

**Comment by Particpant** [comment]
At least on the 6.27.x branch leading up to 6.27.4, here's a couple of interesting changes:
https://github.com/signalapp/Signal-Android/commit/7617cc0a8076cc537db244c5b7b696f3882db084


https://github.com/signalapp/Signal-Android/commit/e5c37576292b4230b8816fc71544d304bf1be512#diff-dd995256db4ee27aa15e7baefaba8f67a5942c79e9b4b9f95eb40c8b26fc7ad9

6.27.2 contains the fix for the long press send button here: https://github.com/signalapp/Signal-Android/commit/ec25831a37a519517c4892794ae2489d1bbf6ecf
Might be worth taking a look at the above two changes at 6.27.2 to start?

**Comment by Particpant** [comment]
Doesn't appear SMS / MMS are removed wholesale until https://github.com/signalapp/Signal-Android/commit/e3ec53c2d01dbc2c781c010a6dd924a37a18d13e in 6.28.0, but it also looks to be one big change instead of several.

**Comment by alexlance** [comment]
I built 6.27.1, .2., .3, they each had the crash bug initially reported.

I built 6.27.4 again, and it can still receive SMS, but it definitely can't send them. If you try to send to someone who's on Signal, it converts the message to a Signal message. If you send a message to someone who's not on Signal you get a "Send failed" message.

On the plus side this means we can tell that SMS sending got removed between versions: 6.26.4 and 6.27.4.

On the less plus side there's 89 commits in:  git log v6.26.3..v6.27.4

**Comment by ubergeek77** [comment]
I don't really have time to actually diagnose and make patches for these issues, but I can offer some suggestions.

For now, 89 commits might be somewhat reasonable to sift through, but eventually they're going to do a huge overhaul, and it's going to be unreasonable to keep cherry picking changes without breaking anything.

So, it might be more realistic to keep things on 6.26.4, and start cherry picking only security-related changes, and API/protocol related changes. This isn't going to be ideal, but I don't think anyone here has both the experience and time to actually maintain a full fork of Signal that maintains SMS and feature parity at the same time.

However, the main messaging format isn't likely to change for a very long time. Signal is fairly backwards compatible too. For example, if someone sends me a message that contains a "spoiler" formatted text, since my old version doesn't support it, I just see the raw unspoilered text as-is. And I believe, if they make a new message format with a different type ID, older Signal apps will either not show the message at all, or just render a blank box. I don't think it will crash.

Obviously this is not ideal at all, but at this point we are just buying time. I'm hoping that someone steps up to either maintain a full SMS enabled fork of Signal, or there is some alternative solution out there that lets me send SMSes and secure messages in the same app. When one pops up, I'll abandon Signal entirely.

If someone wants to step up and be a hero in doing one of those two things, I think the community would be extremely grateful. I'd even pitch in to a code bounty for it.

**Comment by WeareTheDraiken** [comment]
@ubergeek77 I think what you're saying is an excellent Idea honestly,  I want to ask though if someone was just to apply security updates , would  also still beable to apply the new features from signal to the previous version with the sms feature or would that not work?

**Comment by WeareTheDraiken** [comment]
Hey @alexlance and @ubergeek77, I just want to check up on if this whole thing, if there was any progress in solving the issue?

**Comment by ubergeek77** [comment]
Hey @WeareTheDraiken 

Sadly, no. I think the show's over. I am less optimistic now than when I wrote that message.

Very soon (6.30+), Signal will start removing the parts of the codebase responsible for SMS. When that happpens, and long after, it would be an immense effort to maintain a version of Signal that can handle SMS. Management of that kind of fork would require someone with a lot of Java Android experience (of which I have limited), and **_time_** (of which I have *none*). I can't commit to maintaining that and I don't think @alexlance can either.

At this point, I sadly do not have the time or expertise to make up for Signal's unnecessary hostility to their SMS users. Signal's code is changing rapidly, and this kind of simple patch format - an excellent idea and exactly what I would have done - is no longer sustainable.

So what do you do now?

- I am still on 6.15 and it works fine. You could keep using the version you're on until it dies.
- You could hope and pray that a god-tier developer swoops in and commits to maintaining a SMS-compatible Signal version, or crowdfund to entice a developer to do it.
- You could hope someone forks something like [Simple SMS Messenger](https://github.com/SimpleMobileTools/Simple-SMS-Messenger) to add support for sending Signal messages, but I wouldn't count on this.
- You could look into [self-hosting Beeper ](https://github.com/beeper/self-host)and set it up for SMS and Signal messages, but to be honest this would be a chore for anyone to set up and maintain, comes with security concessions, and I can't say I recommend it. I also don't recommend using the non-self-hosted version as they will receive a copy of every message you send, including SMS messages.
- You could get your Signal friends to move to Matrix, and set up an SMS bridge on your phone.
- You could just let go and use two separate apps. I hate to suggest that but here we are.

If anyone has any better alternative options, I'm all ears.

It's been a pleasure o/

**Comment by alexlance** [comment]
Thanks for the excellent description @ubergeek77.

I want this project to continue, but yes, with the upstream changes I don't know how feasible it is to maintain SMS support moving forward.

I'm currently using our v6.26.4 build and it continues to works with SMS, but as detailed above, I was not successful in getting SMS-enabled builds going in the v6.27.x branch.

Note: as the remove-forced-upgrading patch has been applied - it may be possible to keep running SMS-enabled v6.26.4 for as long as one likes (if you are ok with foregoing newer Signal features). 

I will continue to try to make builds in this project, because I still don't appreciate the forced-upgrading in Signal - but from v6.27 (barring a miracle) I won't attempt to retain the SMS functionality.

If someone out there wanted to send a PR to this repo for v6.27 SMS support I'd be delighted to build it and see how far we can push this - but yes, I'm currently stuck.

**Comment by WeareTheDraiken** [comment]
@alexlance, @ubergeek77 Well I'm glad to both of you for trying and seeing to do what you could.

I don't really know what I personally will do now, I guess I'll just hold out and see how long I can keep using this last version or something.

Really a shame.

But thank you, regardless.

**Comment by alexlance** [comment]
Just fyi: 
https://github.com/alexlance/signal-android-classic/issues/9#issuecomment-1929452610
